### ISSUE TITLE
fltkhs-nativefilechooser-simple-app has no menus

### ISSUE THREAD

**Issue by simonmichael** [deech/fltkhs-demos#3]
The help text talks about a File menu, but I see only the default fltkhs-nativefilechooser-simple-app menu. (OSX El Capitan).

**Comment by deech** [comment]
This one's going to take a little more digging. Developed without access to a Mac unfortunately. Thanks!

**Comment by deech** [comment]
Fixed in HEAD of (http://github.com/deech/fltkhs).
